### ISSUE TITLE
Error when running docker

### ISSUE THREAD

**Issue by NMC92** [osm-without-borders/cosmogony_explorer#40]
Bonjour, I hope you're well!

 I have tried building and launching my own Cosmogony, because I have my own genre of this project, albeit on a smaller scale (https://mappumappu.000webhostapp.com/index.html) so it really picked my interest!
 But when I try to do a full flow of the process(meaning I fetch an ...osm.pbf from Geofabrik, build a .json with the Cosmogony project and try to run Cosmogony Explorer with it) I get an error in the tests part. I have tried the Portugal-latest and Poland-latest osm.pbf files. It does, however, build the Explorer with the files already in the Cosmogony project(for example the luxembourg_filtered.osm.pbf in the cosmogony\tests\data folder), although it shows nothing besides the UI of the explorer.
I don't know what I can do to fix it so all help would be appreciated. This would be better discussed through PMs but I can't find any contacts available here. Any help would be much appreciated! Merci beaucoup!
P.S.: There are two images attached, the first with more info of the error and the second with the result of cosmogony json build. Also, if you want to reach out to me, I'll put my e-mail in my own page here. Also, the command I'm running is this:

PATH_TO_COSMOGONY_DIR=../cosmogony_data pipenv run inv -e run-local --cosmogony-file-name=cosmogony_Portugal.json --build-dockers

![error_run_json_cosmogony](https://user-images.githubusercontent.com/50185422/139514887-bd713c7c-86fa-47d9-b834-be0056f34644.jpg)

![result_build_cosmogony](https://user-images.githubusercontent.com/50185422/139532749-5f36b441-ad10-4758-a763-26f24663ea88.jpg)

**Comment by amatissart** [comment]
Hi @NMC92 
As you may have seen, maintenance has been lacking on this repository for the last few months.

The tests that are running in this last step are actually sanity checks on the number of zones found in the cosmogony file. The numbers related to Portugal may be outdated, or are no longer consistent with the configuration used in Cosmogony.
Anyway, this is a bug, the explorer launch should not be blocked by such errors.

As for the absence of map in the UI, it's due to an obsolete style URL in the basemap configuration.

Both issues should be solved by #41. Could you have a try on [this branch](ignore-fail-in-datadashboard-checks)?

**Comment by NMC92** [comment]
Hello @amatissart ! I applied the patch and it's working!! Thank you so much!!
